### PR TITLE
Created a DayDecorator to allow the user to implement it's own decor…

### PR DESCRIPTION
**Pull request by com2ghz**
Created a DayDecorator class to allow the user to implement it's own decoration for each day.

Like example, you want to add a dot, or change the color of some specific dates, you can simply
create your own implementation of DayDecorator.

-Moved the current style to a default DayDecorator(DefaultDayDecorator)

### CODE REVIEW

**Comment by nomanr** [comment]
Have you tested? Is everything working alright? I dont have time to support this library.

**Comment by com2ghz** [comment]
Yes I tested it with the sample activity and it worked good.

I am now implementing this into my production app inside the agenda module where I need to highlight some dates who have appointments.

I will notify you if everything works good without performance problems.

**Comment by com2ghz** [comment]
Please wait with accepting the pull request. I'm having issues with the rendering the days.  I will let you know when it's ready

**Comment by com2ghz** [comment]
It work's like a charm now bro.

You can add your own DayDecorator now by calling setDayDecorator(); If you need to wait on data(like waiting for a REST response) then you want to rerender the calendar again. You can call WeekCalendar.updateUi() method which rerenders the days again.

**Pull request merged**
