### PR TITLE
Register/Unregister event bus in onStart() and onStop() rather than o…

### PR DESCRIPTION
**Pull request by com2ghz**
…nResume() and onPause().
This fixes the following exception:

> 08-01 13:32:35.053 27086-27086/xx.xxxx.crm E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                   Process: xx.xxxx.crm, PID: 27086
>                                                                   java.lang.RuntimeException: Unable to pause activity {xx.xxxx.crm/xx.xxxx.crm.view.CoreActivity}: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class noman.weekcalendar.fragment.WeekFragment registered?
>                                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
>                                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
>                                                                       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
>                                                                       at android.app.ActivityThread.-wrap13(ActivityThread.java)
>                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
>                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                       at android.os.Looper.loop(Looper.java:148)
>                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                       at java.lang.reflect.Method.invoke(Native Method)
>                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                    Caused by: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class noman.weekcalendar.fragment.WeekFragment registered?
>                                                                       at com.squareup.otto.Bus.unregister(Bus.java:290)
>                                                                       at noman.weekcalendar.fragment.WeekFragment.onPause(WeekFragment.java:111)
>                                                                       at android.support.v4.app.Fragment.performPause(Fragment.java:2253)
>                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
>                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)

### CODE REVIEW

**Comment by nomanr** [comment]
Is it ready to be merged?

**Comment by com2ghz** [comment]
Yeah. I have this in in my production version now and it works very good. 

Even NASA use this code to launch a spaceshuttle to the moon :D

**Comment by nomanr** [comment]
lol alright, 
Can you provide the link to your app? Maybe we can add a Apps that are using this library section in Read me?

**Comment by com2ghz** [comment]
I will come back for the reference to the app i'm building. But you can proceed with merging these changes.

**Pull request merged**
